name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download browsers for e2e tests
        run: npx playwright install

      - name: Run e2e tests
        run: npm run e2e

      - name: Run unit tests
        run: npm test
