name: CI Tests

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Download browsers for e2e tests
        run: npx playwright install --with-deps

      - name: Download xvfb
        run: |
          sudo apt update
          sudo apt-get install xvfb -y

      - name: Run unit tests
        run: npm run test-ci

      - name: Run e2e tests
        run: xvfb-run npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
